-- Exercise seed data: 200+ exercises across all major categories

INSERT INTO exercises (name, slug, muscle_groups, primary_muscle, secondary_muscles, equipment, movement_pattern, difficulty, exercise_type, instructions, form_cues, common_mistakes, beginner_modification, advanced_progression, video_search_query, is_compound) VALUES

-- ─── CHEST ───────────────────────────────────────────────────────────────────
('Barbell Bench Press', 'barbell-bench-press', ARRAY['chest','triceps','shoulders'], 'chest', ARRAY['triceps','front deltoid'], ARRAY['barbell','bench'], 'horizontal push', 'beginner', 'strength', ARRAY['Lie flat on bench, feet on floor','Grip bar slightly wider than shoulder-width','Unrack bar, lower to mid-chest with control','Press bar up in a slight arc, fully extending arms'], ARRAY['Keep shoulder blades retracted and depressed','Drive feet into floor for leg drive','Bar should touch chest lightly at bottom','Wrists stacked over elbows'], ARRAY['Flaring elbows too wide','Bouncing bar off chest','Lifting hips off bench','Uneven bar path'], 'Dumbbell bench press or push-ups', 'Close-grip bench press or board press', 'barbell bench press form tutorial', true),

('Incline Barbell Bench Press', 'incline-barbell-bench-press', ARRAY['chest','shoulders','triceps'], 'chest', ARRAY['front deltoid','triceps'], ARRAY['barbell','incline bench'], 'incline push', 'intermediate', 'strength', ARRAY['Set bench to 30-45 degrees','Lie back, grip bar slightly wider than shoulders','Lower bar to upper chest with control','Press up and slightly back'], ARRAY['Keep back firmly on bench','Upper chest should be target — not neck','Retract scapula before unracking'], ARRAY['Setting incline too steep (turns into shoulder press)','Allowing shoulders to protract under load'], 'Incline dumbbell press', 'Incline close-grip bench press', 'incline bench press tutorial', true),

('Dumbbell Bench Press', 'dumbbell-bench-press', ARRAY['chest','triceps','shoulders'], 'chest', ARRAY['triceps','front deltoid'], ARRAY['dumbbells','bench'], 'horizontal push', 'beginner', 'strength', ARRAY['Sit on bench with dumbbells on thighs','Kick up one at a time into position','Lower dumbbells to chest level with elbows at ~75 degrees','Press up and in, bringing dumbbells close at top'], ARRAY['Maintain neutral wrist throughout','Full range of motion — feel the stretch at bottom','Control the descent — 2 seconds down'], ARRAY['Letting dumbbells drift too wide','Not achieving full range of motion','Wrists bending back'], 'Floor press with lighter dumbbells', 'Alternating dumbbell press or single-arm press', 'dumbbell bench press tutorial', true),

('Dumbbell Fly', 'dumbbell-fly', ARRAY['chest'], 'chest', ARRAY['front deltoid'], ARRAY['dumbbells','bench'], 'horizontal pull', 'intermediate', 'isolation', ARRAY['Lie flat on bench, dumbbells held above chest, slight bend in elbows','Open arms wide in a hugging arc until you feel a stretch across chest','Squeeze chest to bring dumbbells back up'], ARRAY['Keep slight bend in elbows throughout — never straight','Think "hugging a barrel"','Control the lowering phase — this is where growth happens'], ARRAY['Using too much weight and turning into press','Straightening elbows (risk of pec tear)','Not getting full stretch at bottom'], 'Cable chest fly at mid-height', 'Cable fly for constant tension', 'dumbbell fly chest exercise', false),

('Cable Chest Fly', 'cable-chest-fly', ARRAY['chest'], 'chest', ARRAY['front deltoid'], ARRAY['cable machine'], 'horizontal pull', 'beginner', 'isolation', ARRAY['Set cables at mid-height, stand in centre','Hold handles, step forward into split stance','With slight bend in elbows, bring hands together in front of chest','Slowly return to start, feeling the stretch'], ARRAY['Constant tension throughout the movement','Keep chest proud — do not round forward','Full range at top — hands should meet or cross'], ARRAY['Using too much weight and losing form','Not fully extending at stretch position'], 'Resistance band chest fly', 'Low-to-high or high-to-low cable fly variations', 'cable chest fly technique', false),

('Push-Up', 'push-up', ARRAY['chest','triceps','shoulders','core'], 'chest', ARRAY['triceps','front deltoid','core'], ARRAY['bodyweight'], 'horizontal push', 'beginner', 'strength', ARRAY['Place hands slightly wider than shoulders','Keep body in straight line from head to heels','Lower chest to just above floor','Push back up explosively'], ARRAY['Keep core braced throughout','Do not let hips sag or pike','Full range — chest nearly touching floor'], ARRAY['Hips sagging','Head drooping forward','Partial range of motion'], 'Knee push-up or elevated push-up', 'Weighted push-up or archer push-up', 'perfect push up form', true),

('Decline Push-Up', 'decline-push-up', ARRAY['chest','triceps','shoulders'], 'chest', ARRAY['triceps','front deltoid'], ARRAY['bodyweight','bench'], 'decline push', 'intermediate', 'strength', ARRAY['Place feet on bench, hands on floor','Keep body rigid','Lower chest toward floor','Push back up'], ARRAY['Keep hips level with body','Do not let lower back arch'], ARRAY['Hips piking up','Head dropping'], 'Regular push-up', 'Weighted decline push-up', 'decline push up form', true),

('Dips (Chest)', 'dips-chest', ARRAY['chest','triceps','shoulders'], 'chest', ARRAY['triceps','front deltoid'], ARRAY['dip bars','parallel bars'], 'vertical push', 'intermediate', 'strength', ARRAY['Grip dip bars, press up to starting position','Lean forward slightly to target chest','Lower yourself by bending elbows until upper arms are parallel to floor','Push back up'], ARRAY['Lean forward for chest focus','Control the descent','Do not lock out at top aggressively'], ARRAY['Staying too upright (hits triceps more)','Going too deep with shoulder issues'], 'Bench dip or assisted dip machine', 'Weighted dips with belt', 'chest dips form', true),

-- ─── BACK ────────────────────────────────────────────────────────────────────
('Conventional Deadlift', 'conventional-deadlift', ARRAY['back','legs','core'], 'lower back', ARRAY['glutes','hamstrings','traps','lats'], ARRAY['barbell'], 'hinge', 'intermediate', 'strength', ARRAY['Stand with feet hip-width, bar over mid-foot','Hinge at hips, grip bar just outside knees','Take a big breath, brace core, push floor away','Keep bar close to body as you stand up tall','Hinge back down with control'], ARRAY['Bar stays close to shins and thighs throughout','Chest up, back flat — no rounding','Hips and shoulders rise at the same rate'], ARRAY['Rounding lower back','Bar drifting away from body','Jerking the bar off floor','Looking up too much'], 'Romanian deadlift with lighter weight', 'Sumo deadlift or deficit deadlift', 'conventional deadlift tutorial', true),

('Barbell Row', 'barbell-row', ARRAY['back','biceps'], 'lats', ARRAY['rhomboids','rear deltoid','biceps'], ARRAY['barbell'], 'horizontal pull', 'intermediate', 'strength', ARRAY['Hinge forward 45 degrees, grip bar slightly wider than shoulders','Drive elbows back past torso, pulling bar to lower chest','Lower bar with control'], ARRAY['Keep back flat and parallel to floor or slightly inclined','Drive elbows — not hands — back','Squeeze shoulder blades at top'], ARRAY['Using too much hip momentum','Letting bar drift toward stomach instead of chest','Rounding upper back'], 'Dumbbell row or seal row', 'Pendlay row or barbell row with pause', 'barbell row form tutorial', true),

('Dumbbell Row', 'dumbbell-row', ARRAY['back','biceps'], 'lats', ARRAY['rhomboids','rear deltoid','biceps'], ARRAY['dumbbells','bench'], 'horizontal pull', 'beginner', 'strength', ARRAY['Place opposite hand and knee on bench for support','Hold dumbbell in working hand, arm extended','Pull dumbbell up to hip, elbow driving past torso','Lower with control'], ARRAY['Keep back flat and parallel to floor','Full range — arm extends fully at bottom','No rotation — keep hips and shoulders square'], ARRAY['Rotating torso to lift the weight','Not getting full range of motion','Pulling with bicep rather than back'], 'Lighter weight with strict form', 'Chest-supported dumbbell row', 'one arm dumbbell row form', true),

('Lat Pulldown', 'lat-pulldown', ARRAY['back','biceps'], 'lats', ARRAY['biceps','rear deltoid'], ARRAY['cable machine'], 'vertical pull', 'beginner', 'strength', ARRAY['Sit at machine, thighs secured under pads','Grip bar wider than shoulders, palms forward','Pull bar down to upper chest, driving elbows down and back','Control bar back up to full arm extension'], ARRAY['Lean back slightly — about 10-15 degrees only','Chest up and proud throughout','Drive elbows down — think "putting elbows in back pockets"'], ARRAY['Leaning back too far (becomes a row)','Pulling to chin instead of chest','Not achieving full stretch at top'], 'Assisted pull-up machine or band pull-down', 'Close-grip or neutral-grip pulldown', 'lat pulldown proper form', true),

('Pull-Up', 'pull-up', ARRAY['back','biceps'], 'lats', ARRAY['biceps','rear deltoid','core'], ARRAY['pull-up bar'], 'vertical pull', 'intermediate', 'strength', ARRAY['Hang from bar with overhand grip, hands slightly wider than shoulders','From dead hang, drive elbows down and back','Pull chin above bar','Lower with control to full hang'], ARRAY['Full dead hang at bottom every rep','Keep chest up — do not round forward','Squeeze lats throughout the movement'], ARRAY['Kipping or swinging for momentum','Partial range of motion','Crossing ankles and swinging'], 'Band-assisted pull-up or lat pulldown', 'Weighted pull-up or L-sit pull-up', 'pull up perfect form', true),

('Chin-Up', 'chin-up', ARRAY['back','biceps'], 'biceps', ARRAY['lats','rear deltoid'], ARRAY['pull-up bar'], 'vertical pull', 'intermediate', 'strength', ARRAY['Hang from bar with underhand grip, shoulder-width','Pull chin above bar by driving elbows toward hips','Lower with control to full hang'], ARRAY['Supinate grip engages biceps more than pull-up','Full range — dead hang at bottom'], ARRAY['Using momentum','Partial range at bottom'], 'Band-assisted chin-up', 'Weighted chin-up', 'chin up vs pull up tutorial', true),

('Seated Cable Row', 'seated-cable-row', ARRAY['back','biceps'], 'rhomboids', ARRAY['lats','biceps','rear deltoid'], ARRAY['cable machine'], 'horizontal pull', 'beginner', 'strength', ARRAY['Sit at cable row machine, feet on pads','Hold handle, keep back upright','Pull handle to lower abdomen, squeezing shoulder blades','Return with control, allowing upper back to stretch'], ARRAY['Keep torso upright — do not lean back to pull','Full stretch at the beginning — let shoulder blades spread','Squeeze hard at end position'], ARRAY['Using torso momentum','Not achieving full scapular retraction at end'], 'Light weight with strict form', 'Single-arm cable row or meadows row', 'seated cable row form', true),

('Face Pull', 'face-pull', ARRAY['shoulders','back'], 'rear deltoid', ARRAY['rotator cuff','rhomboids','traps'], ARRAY['cable machine'], 'horizontal pull', 'beginner', 'isolation', ARRAY['Set cable to upper chest or face height','Hold rope attachment with overhand grip','Pull rope toward face, separating hands as it reaches ears','External rotate wrists so thumbs point back at end'], ARRAY['Elbows should be at ear height throughout','Full external rotation at end position','Light weight — this is a corrective exercise'], ARRAY['Using too much weight','Not achieving external rotation','Elbows dropping below shoulder height'], 'Band pull-apart', 'High cable face pull with added Y-press', 'face pull shoulder health', false),

('Good Morning', 'good-morning', ARRAY['back','legs'], 'lower back', ARRAY['hamstrings','glutes'], ARRAY['barbell'], 'hinge', 'intermediate', 'strength', ARRAY['Place bar across upper back as for squat','Hinge at hips pushing them back, maintaining flat back','Lower torso until nearly parallel to floor','Drive hips forward to return to standing'], ARRAY['Keep back flat throughout — this is a hinging movement','Slight bend in knees','Feel hamstring stretch at bottom'], ARRAY['Rounding lower back','Too much knee bend (becomes a squat)'], 'Romanian deadlift', 'Banded good morning or heavy good morning', 'good morning exercise form', true),

('T-Bar Row', 't-bar-row', ARRAY['back','biceps'], 'lats', ARRAY['rhomboids','biceps','rear deltoid'], ARRAY['barbell','t-bar row machine'], 'horizontal pull', 'intermediate', 'strength', ARRAY['Straddle the bar, hinge forward 45 degrees','Grip handle and pull to chest','Lower with control'], ARRAY['Maintain flat back throughout','Drive elbows back, not up'], ARRAY['Using too much weight and rounding back'], 'Dumbbell row', 'Meadows row', 't-bar row form', true),

-- ─── SHOULDERS ───────────────────────────────────────────────────────────────
('Barbell Overhead Press', 'barbell-overhead-press', ARRAY['shoulders','triceps'], 'front deltoid', ARRAY['triceps','upper chest','serratus'], ARRAY['barbell'], 'vertical push', 'intermediate', 'strength', ARRAY['Hold bar at shoulder height, grip just outside shoulder-width','Brace core, press bar directly overhead','At top, push head through and shrug traps','Lower bar to shoulder level with control'], ARRAY['Keep core braced — no excessive lumbar extension','Bar travels in straight vertical path','Fully lock out overhead with active shoulders'], ARRAY['Leaning back excessively','Bar path drifting forward','Not achieving full lockout'], 'Seated dumbbell press', 'Push press (adding leg drive)', 'overhead press OHP form tutorial', true),

('Dumbbell Shoulder Press', 'dumbbell-shoulder-press', ARRAY['shoulders','triceps'], 'front deltoid', ARRAY['triceps','upper chest'], ARRAY['dumbbells','bench'], 'vertical push', 'beginner', 'strength', ARRAY['Sit on bench with back support, hold dumbbells at shoulder height','Press dumbbells up and slightly inward','Lower back to start with control'], ARRAY['Keep core braced','Do not arch lower back excessively','Neutral wrist position'], ARRAY['Leaning back too much','Letting dumbbells flare out to sides'], 'Seated machine shoulder press', 'Arnold press', 'dumbbell shoulder press form', true),

('Dumbbell Lateral Raise', 'dumbbell-lateral-raise', ARRAY['shoulders'], 'lateral deltoid', ARRAY['traps'], ARRAY['dumbbells'], 'abduction', 'beginner', 'isolation', ARRAY['Stand with dumbbells at sides','Raise arms out to sides until parallel to floor','Thumb side slightly lower than pinky side (internal rotation)','Lower with 3-second count'], ARRAY['Lead with elbows, not hands','Slight forward lean helps target medial delt','Do not shrug traps'], ARRAY['Using too much weight and swinging','Raising above parallel','Full shrugging motion'], 'Cable lateral raise for constant tension', 'Leaning lateral raise for increased range', 'lateral raise form shoulder', false),

('Front Raise', 'front-raise', ARRAY['shoulders'], 'front deltoid', ARRAY['upper chest'], ARRAY['dumbbells','barbell'], 'flexion', 'beginner', 'isolation', ARRAY['Hold dumbbells in front of thighs','Raise arms forward to shoulder height','Lower with control'], ARRAY['Keep slight bend in elbows','Do not swing body for momentum'], ARRAY['Using momentum','Going above shoulder height'], 'Cable front raise', 'Plate front raise', 'front raise shoulder exercise', false),

('Rear Delt Fly', 'rear-delt-fly', ARRAY['shoulders','back'], 'rear deltoid', ARRAY['rhomboids','traps'], ARRAY['dumbbells'], 'horizontal abduction', 'beginner', 'isolation', ARRAY['Hinge forward 45-90 degrees at hips','Hold dumbbells hanging below chest','Raise arms out to sides, squeezing rear delts','Lower with control'], ARRAY['Keep slight bend in elbows','Do not use body momentum','Squeeze at top'], ARRAY['Not hinging forward enough','Using too much weight'], 'Reverse pec deck or cable rear delt fly', 'Cable rear delt fly', 'rear delt fly form', false),

('Arnold Press', 'arnold-press', ARRAY['shoulders','triceps'], 'front deltoid', ARRAY['lateral deltoid','triceps'], ARRAY['dumbbells'], 'vertical push', 'intermediate', 'strength', ARRAY['Start with dumbbells at shoulder height, palms facing you','As you press up, rotate palms forward','At top, palms face away','Reverse rotation on the way down'], ARRAY['Full rotation at top and bottom','Keep movement smooth and controlled'], ARRAY['Using too much weight and losing rotation control'], 'Standard dumbbell press', 'Heavy Arnold press', 'arnold press form arnold schwarzenegger', true),

('Upright Row', 'upright-row', ARRAY['shoulders','back'], 'lateral deltoid', ARRAY['traps','biceps'], ARRAY['barbell','dumbbells'], 'vertical pull', 'intermediate', 'strength', ARRAY['Hold bar with narrow overhand grip','Pull bar straight up, leading with elbows','Elbows should reach ear height at top','Lower with control'], ARRAY['Keep bar close to body','Elbows always above wrists'], ARRAY['Wide grip causing shoulder impingement','Going too heavy'], 'Dumbbell upright row', 'Wider grip to reduce impingement risk', 'upright row form shoulders', true),

('Shrugs', 'shrugs', ARRAY['back'], 'traps', ARRAY['neck'], ARRAY['barbell','dumbbells'], 'elevation', 'beginner', 'isolation', ARRAY['Hold weights at sides','Shrug shoulders straight up toward ears','Hold 1-2 seconds at top','Lower with control'], ARRAY['Do not roll shoulders — straight up and down','Full squeeze at top'], ARRAY['Rolling shoulders (risk of impingement)','Using too much momentum'], 'Machine shrugs', 'Heavy barbell shrug or behind-the-back shrug', 'barbell shrug trap exercise', false),

-- ─── ARMS ─────────────────────────────────────────────────────────────────────
('Barbell Curl', 'barbell-curl', ARRAY['arms'], 'biceps', ARRAY['forearms'], ARRAY['barbell'], 'elbow flexion', 'beginner', 'isolation', ARRAY['Stand holding barbell with underhand shoulder-width grip','Keeping elbows pinned at sides, curl bar to shoulders','Squeeze at top','Lower with control to full extension'], ARRAY['Elbows pinned — do not let them drift forward','Full range — complete extension at bottom','Supinate wrists as you curl'], ARRAY['Swinging back for momentum','Partial range of motion','Elbows drifting forward'], 'EZ-bar curl for wrist comfort', 'Barbell curl with 3-second negative', 'barbell curl form biceps', false),

('Dumbbell Curl', 'dumbbell-curl', ARRAY['arms'], 'biceps', ARRAY['forearms'], ARRAY['dumbbells'], 'elbow flexion', 'beginner', 'isolation', ARRAY['Stand with dumbbells at sides, palms facing forward','Curl right arm up, supinating wrist','Squeeze at top, lower to full extension','Alternate arms or do simultaneously'], ARRAY['Full supination at top','Elbows stay pinned to sides','Full extension at bottom'], ARRAY['Swinging to lift heavier','Not supinating wrist'], 'Supported dumbbell curl', 'Incline dumbbell curl for increased stretch', 'dumbbell curl form bicep', false),

('Hammer Curl', 'hammer-curl', ARRAY['arms'], 'brachialis', ARRAY['biceps','forearms'], ARRAY['dumbbells'], 'elbow flexion', 'beginner', 'isolation', ARRAY['Hold dumbbells with neutral (hammer) grip, palms facing each other','Curl up keeping neutral grip throughout','Do not rotate wrist','Lower with control'], ARRAY['Neutral wrist maintained throughout','Great for forearm and brachialis development'], ARRAY['Rotating wrist at top','Swinging for momentum'], 'Standard dumbbell curl', 'Cross-body hammer curl', 'hammer curl form', false),

('Preacher Curl', 'preacher-curl', ARRAY['arms'], 'biceps', ARRAY['forearms'], ARRAY['barbell','dumbbells','EZ-bar','preacher bench'], 'elbow flexion', 'intermediate', 'isolation', ARRAY['Sit at preacher bench, upper arms resting on pad','Hold bar with underhand grip','Curl bar up to shoulder level','Lower slowly to full extension'], ARRAY['Concentrate tension on bicep at bottom','Full extension without locking out','Slow negative'], ARRAY['Not achieving full range','Going too heavy'], 'Dumbbell preacher curl', 'Unilateral preacher curl', 'preacher curl form bicep peak', false),

('Tricep Pushdown', 'tricep-pushdown', ARRAY['arms'], 'triceps', ARRAY['forearms'], ARRAY['cable machine'], 'elbow extension', 'beginner', 'isolation', ARRAY['Stand at cable, set to high position with rope or bar attachment','Hold with overhand grip, elbows pinned to sides','Push attachment down to full extension','Slowly return to start, keeping elbows fixed'], ARRAY['Elbows pinned to sides throughout','Full extension at bottom','Squeeze triceps hard at bottom'], ARRAY['Letting elbows drift forward','Using body weight to push down'], 'Band pushdown', 'Single-arm pushdown or rope pushdown', 'tricep pushdown form', false),

('Skull Crusher', 'skull-crusher', ARRAY['arms'], 'triceps', ARRAY['chest'], ARRAY['barbell','EZ-bar','dumbbells','bench'], 'elbow extension', 'intermediate', 'isolation', ARRAY['Lie on bench, hold bar with narrow overhand grip','Extend arms straight up above chest','Lower bar toward forehead by bending elbows only','Extend arms back to start'], ARRAY['Elbows pointed straight up — do not flare','Lower slowly and controlled','Elbows should not drift back'], ARRAY['Flaring elbows out to sides','Going too heavy and losing control'], 'Overhead dumbbell extension', 'Close-grip bench press superset', 'skull crusher tricep exercise', false),

('Close-Grip Bench Press', 'close-grip-bench-press', ARRAY['arms','chest'], 'triceps', ARRAY['chest','front deltoid'], ARRAY['barbell','bench'], 'horizontal push', 'intermediate', 'strength', ARRAY['Lie on bench, grip bar at shoulder-width or slightly narrower','Lower bar to lower chest','Press back up, keeping elbows closer to body'], ARRAY['Do not take too narrow a grip (wrist strain)','Elbows stay tucked — not flared'], ARRAY['Grip too narrow','Wrist pain from extreme narrowness'], 'Tricep pushdown', 'Weighted dips', 'close grip bench press triceps', true),

('Overhead Tricep Extension', 'overhead-tricep-extension', ARRAY['arms'], 'triceps', ARRAY[]::text[],ARRAY['dumbbell','cable machine'], 'elbow extension', 'beginner', 'isolation', ARRAY['Hold dumbbell overhead with both hands, or use cable','Bend elbows to lower weight behind head','Extend arms back to overhead position'], ARRAY['Keep elbows close to head','Full stretch at bottom'], ARRAY['Elbows flaring wide','Partial range'], 'Tricep pushdown', 'Single-arm overhead extension', 'overhead tricep extension long head', false),

-- ─── LEGS ────────────────────────────────────────────────────────────────────
('Barbell Back Squat', 'barbell-back-squat', ARRAY['legs','core'], 'quadriceps', ARRAY['glutes','hamstrings','core'], ARRAY['barbell','squat rack'], 'squat', 'intermediate', 'strength', ARRAY['Position bar on upper traps (high bar) or lower traps (low bar)','Stand with feet shoulder-width, toes out 15-30 degrees','Break at hips and knees simultaneously','Descend until thighs at least parallel to floor','Drive through heels to stand'], ARRAY['Knees track over toes throughout','Chest tall, core braced','Full depth — hips crease below knee'], ARRAY['Knees caving in','Forward lean causing good morning squat','Heels rising off floor'], 'Goblet squat with dumbbell', 'Paused squat or heels-elevated squat', 'barbell back squat form tutorial', true),

('Front Squat', 'front-squat', ARRAY['legs','core'], 'quadriceps', ARRAY['glutes','core'], ARRAY['barbell','squat rack'], 'squat', 'advanced', 'strength', ARRAY['Hold bar in front rack position across front delts','Elbows high, chest up','Squat keeping torso more upright than back squat','Full depth','Stand by driving hips up'], ARRAY['Elbows must stay high throughout','More upright torso than back squat','Great for quad development'], ARRAY['Elbows dropping (bar falls forward)','Rounding upper back'], 'Goblet squat', 'Paused front squat', 'front squat form tutorial', true),

('Romanian Deadlift', 'romanian-deadlift', ARRAY['legs','back'], 'hamstrings', ARRAY['glutes','lower back'], ARRAY['barbell','dumbbells'], 'hinge', 'intermediate', 'strength', ARRAY['Stand holding bar at hip level','Hinge at hips pushing them back, slight knee bend','Lower bar along thighs until deep hamstring stretch','Drive hips forward to return to standing'], ARRAY['Bar stays close to legs throughout','Feel stretch in hamstrings not lower back','Maintain slight arch in lower back'], ARRAY['Rounding lower back','Bending knees too much (becomes deadlift)','Bar drifting away from body'], 'Dumbbell RDL', 'Single-leg RDL', 'romanian deadlift RDL form', true),

('Leg Press', 'leg-press', ARRAY['legs'], 'quadriceps', ARRAY['glutes','hamstrings'], ARRAY['leg press machine'], 'squat', 'beginner', 'strength', ARRAY['Sit in leg press machine, feet shoulder-width on platform','Release safety catches','Lower platform until 90 degrees at knee','Press back up without locking out'], ARRAY['Feet higher for more glutes/hamstrings','Feet lower for more quads','Never lock knees out under load'], ARRAY['Knees caving in','Lower back rounding off seat','Locking knees at top'], 'Goblet squat', 'Narrow stance leg press for quad focus', 'leg press foot placement tutorial', true),

('Hack Squat', 'hack-squat', ARRAY['legs'], 'quadriceps', ARRAY['glutes'], ARRAY['hack squat machine'], 'squat', 'intermediate', 'strength', ARRAY['Position in machine, shoulders under pads','Feet shoulder-width, toes slightly out','Descend until thighs parallel or below','Drive through feet to return'], ARRAY['Keep lower back against pad','Knees track over toes','Great quad isolation'], ARRAY['Knees caving','Not going deep enough'], 'Leg press', 'Feet closer together for more quad focus', 'hack squat machine form', true),

('Lunge', 'lunge', ARRAY['legs'], 'quadriceps', ARRAY['glutes','hamstrings'], ARRAY['bodyweight','dumbbells','barbell'], 'lunge', 'beginner', 'strength', ARRAY['Stand tall, step forward with one foot','Lower back knee toward floor','Front knee stays over ankle','Push through front foot to return'], ARRAY['Keep torso upright','Big enough step so front knee does not pass toes','Control the descent'], ARRAY['Front knee caving in','Torso leaning forward','Knee going past toe'], 'Reverse lunge (easier on knees)', 'Walking dumbbell lunge or Bulgarian split squat', 'lunge form tutorial', true),

('Bulgarian Split Squat', 'bulgarian-split-squat', ARRAY['legs'], 'quadriceps', ARRAY['glutes','hamstrings'], ARRAY['dumbbells','barbell','bench'], 'lunge', 'intermediate', 'strength', ARRAY['Stand 2 feet in front of bench','Rest rear foot on bench behind you','Lower hips down until front thigh is parallel','Drive through front foot to stand'], ARRAY['Keep front shin vertical at bottom','Torso upright or slight forward lean','Full range of motion'], ARRAY['Front knee caving in','Leaning too far forward'], 'Reverse lunge', 'Heavy dumbbell or barbell BSS', 'bulgarian split squat form', true),

('Leg Curl', 'leg-curl', ARRAY['legs'], 'hamstrings', ARRAY[]::text[], ARRAY['leg curl machine'], 'knee flexion', 'beginner', 'isolation', ARRAY['Lie prone on machine, heels under pad','Curl heels toward glutes','Squeeze hamstrings at top','Lower with 3-second count'], ARRAY['Full range of motion','Squeeze hard at top','Control the negative'], ARRAY['Hips rising off pad','Using momentum'], 'Dumbbell leg curl', 'Single-leg curl or Nordic curl', 'lying leg curl hamstrings form', false),

('Leg Extension', 'leg-extension', ARRAY['legs'], 'quadriceps', ARRAY[]::text[], ARRAY['leg extension machine'], 'knee extension', 'beginner', 'isolation', ARRAY['Sit in machine, pad resting on top of lower legs','Extend legs to near-straight position','Squeeze quads at top','Lower with control'], ARRAY['Full extension and squeeze at top','Do not lock out aggressively under heavy load'], ARRAY['Not going through full range','Rocking the torso'], 'Bodyweight quad extension', 'Single-leg extension', 'leg extension quad exercise', false),

('Standing Calf Raise', 'standing-calf-raise', ARRAY['legs'], 'calves', ARRAY[]::text[], ARRAY['calf raise machine','step','bodyweight'], 'plantarflexion', 'beginner', 'isolation', ARRAY['Stand on edge of step or platform on balls of feet','Lower heels below platform level','Rise up on toes as high as possible','Pause at top, lower with 3-second count'], ARRAY['Full range — deep stretch at bottom, full contraction at top','Pause at top to avoid bouncing'], ARRAY['Bouncing without getting stretch','Partial range of motion'], 'Seated calf raise', 'Single-leg standing calf raise', 'calf raise full range of motion', false),

('Hip Thrust', 'hip-thrust', ARRAY['legs'], 'glutes', ARRAY['hamstrings'], ARRAY['barbell','bench'], 'hip extension', 'intermediate', 'strength', ARRAY['Sit with upper back against bench, bar across hips','Feet flat on floor, hip-width apart','Drive hips up by squeezing glutes','At top, hips level and parallel to floor','Lower under control'], ARRAY['Squeeze glutes hard at top','Do not hyperextend lower back — ribs should stay down','Chin tucked'], ARRAY['Lower back arching at top','Feet too far or close','Not achieving full hip extension'], 'Glute bridge on floor', 'Single-leg hip thrust or banded hip thrust', 'hip thrust barbell glutes form', true),

('Glute Bridge', 'glute-bridge', ARRAY['legs'], 'glutes', ARRAY['hamstrings'], ARRAY['bodyweight','resistance band'], 'hip extension', 'beginner', 'isolation', ARRAY['Lie on back, knees bent, feet flat on floor','Drive hips up by squeezing glutes','Hold at top for 2 seconds','Lower slowly'], ARRAY['Squeeze glutes — do not just push with legs','Keep ribs down at top','Can add band above knees for activation'], ARRAY['Using hamstrings instead of glutes','Feet too far away'], 'Bodyweight only', 'Hip thrust progression', 'glute bridge form tutorial', false),

-- ─── CORE ────────────────────────────────────────────────────────────────────
('Plank', 'plank', ARRAY['core'], 'core', ARRAY['shoulders','glutes'], ARRAY['bodyweight'], 'anti-extension', 'beginner', 'stability', ARRAY['Forearms on floor, body in straight line','Hold position maintaining neutral spine'], ARRAY['Do not let hips sag or pike','Breathe steadily throughout','Squeeze glutes and brace abs'], ARRAY['Hips sagging','Head dropping','Holding breath'], 'Elevated plank on bench', 'Plank with arm reach or RKC plank', 'plank form core exercise', false),

('Dead Bug', 'dead-bug', ARRAY['core'], 'core', ARRAY['hip flexors'], ARRAY['bodyweight'], 'anti-extension', 'beginner', 'stability', ARRAY['Lie on back, arms extended toward ceiling, knees at 90 degrees','Slowly lower opposite arm and leg toward floor','Return to start, repeat other side','Keep lower back pressed into floor throughout'], ARRAY['Lower back must not lift off floor at any point','Exhale as you lower limbs','Move slowly and controlled'], ARRAY['Lower back arching','Moving too fast'], 'Legs only or arms only', 'Dead bug with resistance band', 'dead bug core exercise form', false),

('Ab Wheel Rollout', 'ab-wheel-rollout', ARRAY['core'], 'core', ARRAY['lats','shoulders'], ARRAY['ab wheel'], 'anti-extension', 'advanced', 'strength', ARRAY['Kneel on floor holding ab wheel','Roll wheel forward until arms extended overhead','Squeeze core to pull back to start'], ARRAY['Keep hips in line — do not let them drop','Exhale on the way back','Move slowly'], ARRAY['Hips sagging','Rolling too far before ready'], 'Kneeling rollout only halfway', 'Standing ab wheel rollout', 'ab wheel rollout form', false),

('Hanging Leg Raise', 'hanging-leg-raise', ARRAY['core'], 'core', ARRAY['hip flexors'], ARRAY['pull-up bar'], 'flexion', 'intermediate', 'strength', ARRAY['Hang from bar with overhand grip','Keep slight bend in elbows','Raise legs until parallel to floor (or higher)','Lower with control without swinging'], ARRAY['Control the swing at bottom','Focus on posterior pelvic tilt — curl hips under at top','Breathe out as you raise'], ARRAY['Swinging for momentum','Not going high enough'], 'Knee raise instead of straight leg', 'Toes to bar', 'hanging leg raise form', false),

('Russian Twist', 'russian-twist', ARRAY['core'], 'obliques', ARRAY['core'], ARRAY['bodyweight','weight plate','medicine ball'], 'rotation', 'beginner', 'strength', ARRAY['Sit with knees bent, feet slightly off floor, torso at 45 degrees','Hold hands or weight in front','Rotate torso side to side'], ARRAY['Keep feet elevated for more difficulty','Rotate from torso, not just arms'], ARRAY['Moving arms without rotating torso'], 'Feet on floor for easier version', 'Weighted plate Russian twist', 'russian twist obliques form', false),

('Cable Crunch', 'cable-crunch', ARRAY['core'], 'core', ARRAY[]::text[], ARRAY['cable machine'], 'flexion', 'beginner', 'strength', ARRAY['Kneel in front of cable, hold rope behind head','Crunch down pulling elbows toward knees','Keep hips stationary — movement from spine only'], ARRAY['Do not pull with arms — abs do the work','Hold contraction at bottom'], ARRAY['Using hip flexors to fold forward','Moving hips'], 'Bodyweight crunches', 'Heavy cable crunch', 'cable crunch abs form', false),

('Hollow Body Hold', 'hollow-body-hold', ARRAY['core'], 'core', ARRAY['hip flexors'], ARRAY['bodyweight'], 'anti-extension', 'intermediate', 'stability', ARRAY['Lie on back, press lower back into floor','Extend arms overhead and legs out low','Hold position — body forms a dish shape'], ARRAY['Lower back stays pressed into floor throughout','Arms and legs low but not touching floor','Build time progressively'], ARRAY['Lower back arching off floor','Arms reaching too far back'], 'Knees bent modification', 'Hollow body rock', 'hollow body hold gymnastics core', false),

-- ─── CARDIO ─────────────────────────────────────────────────────────────────
('Treadmill Run', 'treadmill-run', ARRAY['cardio'], 'cardiovascular system', ARRAY['legs'], ARRAY['treadmill'], 'locomotion', 'beginner', 'cardio', ARRAY['Set appropriate speed for session goal','Maintain upright posture','Land midfoot, not heel'], ARRAY['Slight forward lean','Arms at 90 degrees, not crossing body'], ARRAY['Leaning on handrails','Heel striking heavily'], 'Treadmill walk', 'Incline treadmill or sprint intervals', 'treadmill running form', false),

('Rowing Machine', 'rowing-machine', ARRAY['cardio','back','legs'], 'cardiovascular system', ARRAY['lats','legs','core'], ARRAY['rowing machine'], 'pull', 'beginner', 'cardio', ARRAY['Sit at rower, feet strapped in','Drive legs first, then lean back, then pull arms to lower chest','Reverse: arms, lean forward, legs','Repeat rhythmically'], ARRAY['Sequence: legs, body, arms on drive. Arms, body, legs on recovery','Keep back flat throughout'], ARRAY['Rounding back','All arms and no legs'], 'Low resistance rowing', 'High intensity rowing intervals', 'rowing machine form technique', false),

('Assault Bike', 'assault-bike', ARRAY['cardio'], 'cardiovascular system', ARRAY['legs','arms'], ARRAY['assault bike'], 'push-pull', 'beginner', 'cardio', ARRAY['Sit with slight forward lean','Push and pull handles simultaneously while pedaling','Maintain consistent effort'], ARRAY['Arms and legs should work together','Control breathing'], ARRAY['Hunching over handle'], 'Low resistance steady state', 'Max effort intervals', 'assault bike hiit workout', false),

('Jump Rope', 'jump-rope', ARRAY['cardio','legs'], 'cardiovascular system', ARRAY['calves','coordination'], ARRAY['jump rope'], 'plyometric', 'beginner', 'cardio', ARRAY['Hold handles, rope behind you','Swing rope overhead','Jump as rope passes under feet','Land on balls of feet'], ARRAY['Jump just high enough to clear rope','Wrists do the rotation, not whole arms'], ARRAY['Jumping too high','Landing on heels'], 'Slow practice without rope', 'Double-unders', 'jump rope tutorial beginners', false),

('Box Jump', 'box-jump', ARRAY['legs','cardio'], 'quadriceps', ARRAY['glutes','hamstrings'], ARRAY['plyo box'], 'plyometric', 'intermediate', 'power', ARRAY['Stand in front of box, athletic stance','Swing arms and load hips','Explode onto box, landing softly in athletic position','Step down one foot at a time'], ARRAY['Land soft — quiet feet','Full extension at take-off','Step down rather than jumping down to protect joints'], ARRAY['Landing with knees caving','Jumping down from box'], 'Step-up to box', 'Higher box or weighted box jump', 'box jump proper form', false),

('Burpee', 'burpee', ARRAY['cardio','chest','legs','core'], 'cardiovascular system', ARRAY['chest','legs','shoulders'], ARRAY['bodyweight'], 'full body', 'beginner', 'conditioning', ARRAY['Stand, then drop hands to floor','Jump or step feet back to plank','Chest to floor','Push up, jump feet to hands','Explode up with jump and clap overhead'], ARRAY['Move at sustainable pace','Focus on form over speed'], ARRAY['Sagging hips in plank','Not hitting full range'], 'Step-back burpee (no jump)', 'Add push-up and tuck jump', 'burpee exercise form tutorial', true),

('Mountain Climber', 'mountain-climber', ARRAY['cardio','core'], 'core', ARRAY['hip flexors','shoulders'], ARRAY['bodyweight'], 'anti-extension', 'beginner', 'conditioning', ARRAY['Start in push-up position','Drive one knee toward chest','Rapidly alternate legs'], ARRAY['Keep hips level — do not pike','Brace core throughout'], ARRAY['Hips rising','Shoulders collapsing'], 'Slow mountain climbers', 'Cross-body mountain climbers', 'mountain climber exercise form', false),

-- ─── BODYWEIGHT ───────────────────────────────────────────────────────────────
('Bodyweight Dip', 'bodyweight-dip', ARRAY['chest','arms','shoulders'], 'triceps', ARRAY['chest','front deltoid'], ARRAY['dip bars','parallel bars'], 'vertical push', 'intermediate', 'strength', ARRAY['Grip bars, extend arms to lift body','Lower by bending elbows until upper arms parallel to floor','Press back to start'], ARRAY['Stay upright for tricep focus, lean forward for chest','Full range of motion'], ARRAY['Not going deep enough','Locking out aggressively'], 'Bench dip or assisted dip', 'Weighted dip', 'bodyweight dip form tutorial', true),

('Pistol Squat', 'pistol-squat', ARRAY['legs','core'], 'quadriceps', ARRAY['glutes','core'], ARRAY['bodyweight'], 'squat', 'advanced', 'strength', ARRAY['Stand on one leg, extend other leg in front','Squat down on standing leg as low as possible','Extend opposite leg parallel to floor throughout','Stand back up'], ARRAY['Keep heel on floor throughout','Use a counterbalance if needed','Progress slowly'], ARRAY['Heel lifting','Torso collapsing forward'], 'Box squat on one leg', 'Weighted pistol squat', 'pistol squat tutorial progression', true),

('Nordic Curl', 'nordic-curl', ARRAY['legs'], 'hamstrings', ARRAY[]::text[], ARRAY['partner','nordic bench'], 'knee flexion', 'advanced', 'strength', ARRAY['Kneel with feet secured behind you','Keeping body straight, lower torso forward as slowly as possible','Catch yourself with hands, push back to start'], ARRAY['Move as slowly as possible on the way down','This is extremely difficult — start with partial reps'], ARRAY['Bending at hips to make easier'], 'Leg curl machine', 'Unassisted Nordic curl', 'nordic curl hamstring exercise', false),

('Pike Push-Up', 'pike-push-up', ARRAY['shoulders','arms'], 'front deltoid', ARRAY['triceps'], ARRAY['bodyweight'], 'vertical push', 'intermediate', 'strength', ARRAY['Start in downward dog position, hips high','Lower head toward floor by bending elbows','Push back up'], ARRAY['Hips should stay high throughout','Good progression toward handstand push-up'], ARRAY['Letting hips drop to regular push-up position'], 'Regular push-up', 'Elevated pike push-up', 'pike push up shoulder exercise', true),

('Inverted Row', 'inverted-row', ARRAY['back','biceps'], 'rhomboids', ARRAY['lats','biceps'], ARRAY['barbell','smith machine','rings'], 'horizontal pull', 'beginner', 'strength', ARRAY['Set bar at waist height, hang underneath with overhand grip','Body straight from head to heels','Pull chest up to bar, squeezing shoulder blades','Lower with control'], ARRAY['Keep body rigid — do not let hips sag','Pull to chest, not chin'], ARRAY['Hips drooping','Using legs to help'], 'More upright position for easier version', 'Add weight vest or elevate feet', 'inverted row form tutorial', true),

('Diamond Push-Up', 'diamond-push-up', ARRAY['arms','chest'], 'triceps', ARRAY['chest'], ARRAY['bodyweight'], 'horizontal push', 'intermediate', 'strength', ARRAY['Form diamond shape with hands under chest','Perform push-up keeping elbows close to body'], ARRAY['Keep elbows tucked','Do not let wrists bend back'], ARRAY['Elbows flaring wide'], 'Regular push-up first', 'Weighted diamond push-up', 'diamond push up tricep form', false),

('Wide Push-Up', 'wide-push-up', ARRAY['chest'], 'chest', ARRAY['triceps','front deltoid'], ARRAY['bodyweight'], 'horizontal push', 'beginner', 'strength', ARRAY['Hands wider than shoulders','Perform push-up with elbows flaring at ~60 degrees'], ARRAY['Wider than normal to target outer chest'], ARRAY['Going too wide and losing shoulder safety'], 'Regular push-up', 'Weighted wide push-up', 'wide push up chest exercise', false),

-- ─── ADDITIONAL COMPOUND MOVEMENTS ──────────────────────────────────────────
('Power Clean', 'power-clean', ARRAY['legs','back','shoulders'], 'quadriceps', ARRAY['glutes','traps','shoulders'], ARRAY['barbell'], 'olympic lift', 'advanced', 'power', ARRAY['Bar over mid-foot, similar deadlift start position','First pull: drive legs, keeping bar close','Second pull: explosive hip extension as bar reaches hips','Pull bar high with straight elbows as you drop under','Catch in front rack position at quarter squat','Stand up'], ARRAY['Bar stays close throughout','Explosive hip drive is key','Catch with elbows high in rack position'], ARRAY['Bar swinging away from body','No hip explosion'], 'Hang power clean', 'Full squat clean', 'power clean tutorial beginner', true),

('Trap Bar Deadlift', 'trap-bar-deadlift', ARRAY['legs','back'], 'quadriceps', ARRAY['glutes','hamstrings','lower back'], ARRAY['trap bar'], 'hinge', 'beginner', 'strength', ARRAY['Stand inside trap bar, feet hip-width','Grip handles, hinge and squat slightly','Push floor away to stand while keeping back flat'], ARRAY['More knee-friendly than conventional deadlift','Great for beginners learning to hinge'], ARRAY['Rounding back','Bar drifting forward'], 'Romanian deadlift', 'Conventional deadlift', 'trap bar deadlift form tutorial', true),

('Sumo Deadlift', 'sumo-deadlift', ARRAY['legs','back'], 'glutes', ARRAY['quadriceps','adductors','hamstrings'], ARRAY['barbell'], 'hinge', 'intermediate', 'strength', ARRAY['Wide stance, toes pointing out 45-60 degrees','Grip bar inside legs','Keep torso more upright than conventional','Drive hips through to stand'], ARRAY['Push knees out over toes throughout','More glute-dominant than conventional'], ARRAY['Knees caving in','Torso too horizontal'], 'Conventional deadlift', 'Deficit sumo deadlift', 'sumo deadlift form tutorial', true),

('Goblet Squat', 'goblet-squat', ARRAY['legs'], 'quadriceps', ARRAY['glutes','core'], ARRAY['dumbbell','kettlebell'], 'squat', 'beginner', 'strength', ARRAY['Hold dumbbell vertically at chest with both hands','Feet shoulder-width, toes out','Squat to full depth, keeping elbows inside knees','Stand by driving through heels'], ARRAY['Great for teaching squat mechanics','Keep elbows inside knees at bottom'], ARRAY['Heels rising','Forward lean'], 'Bodyweight squat', 'Front squat progression', 'goblet squat form tutorial', true),

('Landmine Press', 'landmine-press', ARRAY['shoulders','chest'], 'front deltoid', ARRAY['chest','triceps'], ARRAY['barbell','landmine attachment'], 'press', 'intermediate', 'strength', ARRAY['Hold bar end at shoulder, feet staggered','Press bar up and forward in an arc','Lower with control'], ARRAY['Good shoulder-friendly pressing option','Arc path is natural for shoulder joint'], ARRAY['Using too much leg drive'], 'Dumbbell shoulder press', 'Single-arm landmine press', 'landmine press form', true),

('Cable Pull-Through', 'cable-pull-through', ARRAY['legs','back'], 'glutes', ARRAY['hamstrings'], ARRAY['cable machine'], 'hinge', 'beginner', 'strength', ARRAY['Face away from cable, rope between legs','Hinge at hips, rope pulls back through legs','Drive hips forward to return upright'], ARRAY['Push hips back not down','Great hip hinge teacher'], ARRAY['Squatting instead of hinging'], 'Romanian deadlift', 'Kettlebell swing', 'cable pull through glutes form', false),

('Kettlebell Swing', 'kettlebell-swing', ARRAY['legs','back','cardio'], 'glutes', ARRAY['hamstrings','lower back'], ARRAY['kettlebell'], 'hinge', 'intermediate', 'power', ARRAY['Hold kettlebell, hike it back between legs','Explosively drive hips forward','Bell swings to shoulder height via hip drive — not arms','Let bell fall back, hinge again'], ARRAY['Power comes from hips not arms','Hike the bell back with force','At top — glutes squeezed, core braced'], ARRAY['Squatting instead of hinging','Using arms to lift'], 'Romanian deadlift for hip hinge practice', 'Heavy kettlebell swing or single-arm swing', 'kettlebell swing form tutorial', true),

('Incline Dumbbell Curl', 'incline-dumbbell-curl', ARRAY['arms'], 'biceps', ARRAY['forearms'], ARRAY['dumbbells','incline bench'], 'elbow flexion', 'intermediate', 'isolation', ARRAY['Sit on incline bench at 45-60 degrees, arms hanging','Curl both or alternate dumbbells','Greater stretch at bottom due to shoulder extension'], ARRAY['Full stretch at bottom is the benefit of this exercise','Supinate wrist on the way up'], ARRAY['Not getting full stretch'], 'Standard dumbbell curl', 'Incline hammer curl', 'incline dumbbell curl form bicep peak', false),

('Zottman Curl', 'zottman-curl', ARRAY['arms'], 'biceps', ARRAY['brachialis','forearms'], ARRAY['dumbbells'], 'elbow flexion', 'intermediate', 'isolation', ARRAY['Start with underhand grip, curl up to top','At top, rotate to overhand grip','Lower slowly with overhand grip','Rotate back to underhand for next rep'], ARRAY['Slow pronated negative trains forearms and brachialis','Great for full arm development'], ARRAY['Rushing the rotation'], 'Dumbbell curl', 'Heavier Zottman curl', 'zottman curl form', false),

('Reverse Curl', 'reverse-curl', ARRAY['arms'], 'brachialis', ARRAY['forearms','biceps'], ARRAY['barbell','dumbbells'], 'elbow flexion', 'beginner', 'isolation', ARRAY['Hold bar with overhand (pronated) grip','Curl as with standard barbell curl'], ARRAY['Trains brachialis and forearms more than supinated curl'], ARRAY['Losing wrist alignment'], 'Hammer curl', 'Reverse wrist curl for forearm focus', 'reverse curl forearm brachialis', false),

('Chest-Supported Row', 'chest-supported-row', ARRAY['back','biceps'], 'rhomboids', ARRAY['lats','rear deltoid','biceps'], ARRAY['dumbbells','incline bench'], 'horizontal pull', 'beginner', 'strength', ARRAY['Lie face-down on incline bench','Hold dumbbells hanging below','Row both dumbbells up toward hips','Lower with control'], ARRAY['Eliminates cheating with lower back','Great for isolating upper back'], ARRAY['Arching off pad'], 'Seated cable row', 'Chest-supported machine row', 'chest supported row form tutorial', true),

('Bent-Over Reverse Fly', 'bent-over-reverse-fly', ARRAY['shoulders','back'], 'rear deltoid', ARRAY['rhomboids'], ARRAY['dumbbells'], 'horizontal abduction', 'beginner', 'isolation', ARRAY['Hinge forward 45 degrees','Raise dumbbells out to sides in arc motion','Squeeze rear delts at top'], ARRAY['Keep slight bend in elbows','Do not use traps to shrug weight up'], ARRAY['Using traps instead of rear delts'], 'Cable rear delt fly', 'Heavier dumbbell rear fly', 'reverse fly rear deltoid form', false),

('Concentration Curl', 'concentration-curl', ARRAY['arms'], 'biceps', ARRAY[]::text[], ARRAY['dumbbell'], 'elbow flexion', 'beginner', 'isolation', ARRAY['Sit on bench, elbow braced against inner thigh','Curl dumbbell toward shoulder','Full supination and squeeze at top'], ARRAY['Brace elbow completely — no movement','Full range and supination'], ARRAY['Elbow not braced','Partial range'], 'Dumbbell curl', 'Cable concentration curl', 'concentration curl form bicep peak', false),

('Spider Curl', 'spider-curl', ARRAY['arms'], 'biceps', ARRAY[]::text[], ARRAY['dumbbells','barbell','incline bench'], 'elbow flexion', 'intermediate', 'isolation', ARRAY['Lie face-down on incline bench','Let arms hang vertically','Curl weight up keeping upper arm vertical'], ARRAY['Upper arm stays perpendicular to floor throughout','Great peak contraction'], ARRAY['Upper arm drifting back'], 'Preacher curl', 'Cable spider curl', 'spider curl bicep exercise', false),

('Tate Press', 'tate-press', ARRAY['arms'], 'triceps', ARRAY[]::text[], ARRAY['dumbbells','bench'], 'elbow extension', 'intermediate', 'isolation', ARRAY['Lie on bench, hold dumbbells above chest with overhand grip','Lower dumbbells by flaring elbows to the side, toward chest','Extend back up'], ARRAY['Elbows flare out — this is correct for this exercise','Targets triceps from unique angle'], ARRAY['Too much weight'], 'Skull crusher', 'Heavy Tate press', 'tate press tricep exercise', false),

('Seated Leg Curl', 'seated-leg-curl', ARRAY['legs'], 'hamstrings', ARRAY[]::text[], ARRAY['seated leg curl machine'], 'knee flexion', 'beginner', 'isolation', ARRAY['Sit in machine, legs extended on pad','Curl heels toward glutes','Squeeze hamstrings at bottom','Return with control'], ARRAY['Full extension at start','Squeeze hard at bottom'], ARRAY['Not achieving full range'], 'Lying leg curl', 'Single-leg seated curl', 'seated leg curl hamstrings', false),

('Sissy Squat', 'sissy-squat', ARRAY['legs'], 'quadriceps', ARRAY[]::text[], ARRAY['bodyweight'], 'knee extension', 'advanced', 'isolation', ARRAY['Stand holding support, feet together','Rise on toes, lean back and bend knees simultaneously','Lower until thighs parallel or below','Return to start'], ARRAY['Strong quad isolation with deep stretch','Hold support until comfortable'], ARRAY['Going too fast','Not building up range gradually'], 'Leg extension machine', 'Weighted sissy squat', 'sissy squat quad exercise', false),

('Step-Up', 'step-up', ARRAY['legs'], 'quadriceps', ARRAY['glutes'], ARRAY['step','box','bench'], 'lunge', 'beginner', 'strength', ARRAY['Stand in front of box or step','Step up with one foot, drive through heel to stand on box','Step back down with control','Alternate legs or complete all reps one side'], ARRAY['Drive through heel of the working leg','Keep torso upright'], ARRAY['Pushing off back foot too much'], 'Lower box height', 'Weighted step-up with dumbbells', 'step up exercise form', true),

('Reverse Lunge', 'reverse-lunge', ARRAY['legs'], 'quadriceps', ARRAY['glutes','hamstrings'], ARRAY['bodyweight','dumbbells'], 'lunge', 'beginner', 'strength', ARRAY['Stand tall','Step backward with one foot, lowering knee to floor','Front knee stays over ankle','Push through front foot to return'], ARRAY['Easier on knees than forward lunge','Keep torso upright'], ARRAY['Front knee caving','Too short a step'], 'Bodyweight squat', 'Forward lunge progression', 'reverse lunge form tutorial', true),

('Pause Squat', 'pause-squat', ARRAY['legs','core'], 'quadriceps', ARRAY['glutes'], ARRAY['barbell'], 'squat', 'advanced', 'strength', ARRAY['Perform back squat','At bottom position, pause for 3-5 seconds','No bouncing — maintain tension throughout pause','Stand up'], ARRAY['Stay tight during pause — do not relax','Builds strength out of the hole'], ARRAY['Relaxing in the hole','Losing position during pause'], 'Regular back squat', 'Heavier pause squat', 'pause squat form tutorial', true),

('Romanian Split Squat', 'romanian-split-squat', ARRAY['legs'], 'hamstrings', ARRAY['glutes'], ARRAY['dumbbells','barbell'], 'lunge', 'intermediate', 'strength', ARRAY['Take a long split stance','Keeping back leg straight, hinge forward at hip and lower bar along front leg','Feel hamstring stretch of front leg'], ARRAY['More hamstring-focused than standard BSS','Long forward lean is intentional'], ARRAY['Not enough forward lean'], 'Romanian deadlift', 'Bulgarian split squat', 'romanian split squat hamstring', true)

ON CONFLICT (slug) DO NOTHING;
